In [1]:
import numpy as np
import pandas as pd

In [4]:
class Store:
    def __init__(self, name):
        self.name = name
        self.isles = {1:['pizza', 'frozen vegetables', 'frozen fruit'], 
             2:['dumplings', 'chicken tenders', 'hot pockets'],
             3:['milk', 'yogurt', 'cheese'], 
             4:['chicken','beef','pork'],
             5:['bread', 'bagels', 'muffins'],
             6:['bananas', 'apples', 'oranges']
            }
        
        self.isle_mapping = {1:'frozen foods',
                             2: 'frozen foods 2',
                             3:'dairy',
                             4: 'meat',
                             5:'bread',
                             6: 'fruit'} #prob don't need this dict tho
        self.grocery_map = [
        [3,3,3,4,4,4],
        [0,0,0,0,0,0],
        [5,0,1,2,0,6],    
        [5,0,1,2,0,6],
        [5,0,1,2,0,6],
        [0,0,0,0,0,0]
        ]
        
    def showMap(self):
        print(np.matrix(self.grocery_map))
        
    def isleDistances(self): 
        """
        BFS between the center of each pair of isles. 
        Creates a new graph where each weight is isle length 
        """
        
vons = Store('Vons')
vons.showMap()

[[3 3 3 4 4 4]
 [0 0 0 0 0 0]
 [5 0 1 2 0 6]
 [5 0 1 2 0 6]
 [5 0 1 2 0 6]
 [0 0 0 0 0 0]]


- How to account for boundaries between isles? (so not to walk through walls)

- do isle id numbers matter if the optimization just looks for distance?
- using 0 for walkway in grocery_map, otherwise cannot walk through. 
- when using an actual floorplan, must decide on resolution of map
- isles should be one isle
- should there be an isle list for general category, not location (eg cheese may be in a different isle than the rest of the dairy)


- at what point on the isle should it be the designated arrival point? (since we don't know where exactly on the isle the item will be.
    - try just the middle of the isle, then try to see if there is any change in optimal paths when varying arrival points
    
    
## Formulated as a graph problem:
- adjacency matrix is the average length of path between each isle
  -  AKA avg number of pixels/steps (where you're allowed to walk) from one isle to the next
  - must calculate each possible path, and look at variance in distance.  
  - How is this different from using center of isle as arrival point?
  
  
## PIPELINE
- figure out how to find discrete length between pixels
- Make adjacency matrix for average distance between isles
    - each isle will have to be split up into multiple chunks of minimum resolution to compute distances between every combination of pixels between isles
    
- Find traversal for shortest path given that you must visit the isles your grocery list requires
  -  uh oh this sounds like travelling salesman problem
  
- Should include a starting point (entrances) and ending point (cash registers)
    - should load both starting points, and user selects which one when they walk in.  
- how to return this path on the 2d map
- Do distances in adjacency matrix after this reflect actual distance?


dictionary pipeline:
- webscrape grocery store websites to obtain a dict of isles and their items

### Assumptions:
- The shortest path from one isle to another on the weighted graph is only one edge long (the direct one between those isles)

### Research questions
- how does output change the more complicated of a floorplan it gets?  
- What about when isles are more broken down? (Resulting from more info about isle contents and their locations on that isle) 
- How does discrete distance w/ obstacles (isles) compare and contrast with euclidean distance?

### finding discrete distance between two points

should search for next pixel be like this: (this has most been amended with BFS I think)

` Where X is next spot in search and O is current loc   
  X            XXX
 XOX  or like  XOX   ? <--- the latter one you can cut corners with
  X            XXX`

In [ ]:
def generate_adj_mat(groc_map):
    """
    1. Convert grocery map to map with unique id's for each pixel
    2. Unique id's are values for their respective isle key
    3. Calculate avg dist b/w each isle
    4. Return adjacency matrix where each value is avg dist
    """
    isle_ids = np.unique(grocery_map)
    for i in isle_ids
    
    #use find_dist iteratively for every combination of pixels between isles

In [11]:
def linearize_list(groc_list, groc_map):
    """
    
    """
    input_ids = [] #these are the isles that must be visited
    
    for item in groc_list: #maps item to floorplan IDs
        for isle, contents in isles.items(): #isles was defined earlier
            if item in contents:
                input_ids.append(isle)

    new_map = groc_map
    for i in input_ids:
        for x in groc_map:
            for y in x:
                
    return mapping

[6, 4, 2]

Sometime will be overlap between isle key (eg 'fruit') and value from that key (eg 'fruit', again) because sometimes you just want some nonspecifc item from that isle. 

Store object should have a matrix of isle-item matrix, that connects to a dict?

linearizeList function: input is a list, output is a map with stars (location of isle) and dashes (path to follow).
- reordered how?  BFS? 
- 

In [3]:
l = [0]

def makeList():
    l = ['Grocery List']
    for i in l:
        if i != 'end':
            l.append(input('Enter an item: '))

    print(l)
    return l